1375657524602b79

Content: var
Type: KEYWORD
Line: 1
Col: 1
------------------------


Content: exp1
Type: IDENTIFIER
Line: 1
Col: 5
------------------------


Content: :
Type: DELIMITER
Line: 1
Col: 9
------------------------


Content: f32
Type: KEYWORD
Line: 1
Col: 11
------------------------


Content: =
Type: OP_ASSIGNMENT
Line: 1
Col: 15
------------------------


Content: 10.13
Type: LITERAL_FLOAT
Line: 1
Col: 17
------------------------


Content: +
Type: OP_ARITHMETIC
Line: 1
Col: 22
------------------------


Content: 15.0
Type: LITERAL_FLOAT
Line: 1
Col: 25
------------------------


Content: ;
Type: DELIMITER
Line: 1
Col: 29
------------------------


Content: var
Type: KEYWORD
Line: 2
Col: 1
------------------------


Content: exp2
Type: IDENTIFIER
Line: 2
Col: 5
------------------------


Content: :
Type: DELIMITER
Line: 2
Col: 9
------------------------


Content: f32
Type: KEYWORD
Line: 2
Col: 11
------------------------


Content: =
Type: OP_ASSIGNMENT
Line: 2
Col: 15
------------------------


Content: 10.13
Type: LITERAL_FLOAT
Line: 2
Col: 17
------------------------


Content: +
Type: OP_ARITHMETIC
Line: 2
Col: 22
------------------------


Content: 15.0
Type: LITERAL_FLOAT
Line: 2
Col: 25
------------------------


Content: /
Type: OP_ARITHMETIC
Line: 2
Col: 29
------------------------


Content: 3
Type: LITERAL_INT
Line: 2
Col: 32
------------------------


Content: ;
Type: DELIMITER
Line: 2
Col: 33
------------------------


Content: var
Type: KEYWORD
Line: 3
Col: 1
------------------------


Content: exp3
Type: IDENTIFIER
Line: 3
Col: 5
------------------------


Content: :
Type: DELIMITER
Line: 3
Col: 9
------------------------


Content: f32
Type: KEYWORD
Line: 3
Col: 11
------------------------


Content: =
Type: OP_ASSIGNMENT
Line: 3
Col: 15
------------------------


Content: 45.4
Type: LITERAL_FLOAT
Line: 3
Col: 17
------------------------


Content: -
Type: OP_ARITHMETIC
Line: 3
Col: 21
------------------------


Content: 12.865
Type: LITERAL_FLOAT
Line: 3
Col: 24
------------------------


Content: *
Type: OP_ARITHMETIC
Line: 3
Col: 30
------------------------


Content: (
Type: DELIMITER
Line: 3
Col: 33
------------------------


Content: 23
Type: LITERAL_INT
Line: 3
Col: 34
------------------------


Content: /
Type: OP_ARITHMETIC
Line: 3
Col: 36
------------------------


Content: 2
Type: LITERAL_INT
Line: 3
Col: 39
------------------------


Content: )
Type: DELIMITER
Line: 3
Col: 40
------------------------


Content: ;
Type: DELIMITER
Line: 3
Col: 41
------------------------


Content: var
Type: KEYWORD
Line: 4
Col: 1
------------------------


Content: exp4
Type: IDENTIFIER
Line: 4
Col: 5
------------------------


Content: :
Type: DELIMITER
Line: 4
Col: 9
------------------------


Content: f32
Type: KEYWORD
Line: 4
Col: 11
------------------------


Content: =
Type: OP_ASSIGNMENT
Line: 4
Col: 15
------------------------


Content: 235.4
Type: LITERAL_FLOAT
Line: 4
Col: 17
------------------------


Content: -
Type: OP_ARITHMETIC
Line: 4
Col: 22
------------------------


Content: Add
Type: IDENTIFIER
Line: 4
Col: 25
------------------------


Content: (
Type: DELIMITER
Line: 4
Col: 28
------------------------


Content: 10
Type: LITERAL_INT
Line: 4
Col: 29
------------------------


Content: ,
Type: DELIMITER
Line: 4
Col: 31
------------------------


Content: 20
Type: LITERAL_INT
Line: 4
Col: 33
------------------------


Content: )
Type: DELIMITER
Line: 4
Col: 35
------------------------


Content: *
Type: OP_ARITHMETIC
Line: 4
Col: 36
------------------------


Content: (
Type: DELIMITER
Line: 4
Col: 39
------------------------


Content: 23
Type: LITERAL_INT
Line: 4
Col: 40
------------------------


Content: /
Type: OP_ARITHMETIC
Line: 4
Col: 42
------------------------


Content: 2
Type: LITERAL_INT
Line: 4
Col: 45
------------------------


Content: )
Type: DELIMITER
Line: 4
Col: 46
------------------------


Content: ;
Type: DELIMITER
Line: 4
Col: 47
------------------------


Content: 
Type: END_OF_FILE
Line: 6
Col: 0
------------------------

