938b9cdba844511e

Content: fun
Type: KEYWORD
Line: 1
Col: 1
------------------------


Content: Add
Type: IDENTIFIER
Line: 1
Col: 5
------------------------


Content: (
Type: DELIMITER
Line: 1
Col: 8
------------------------


Content: const
Type: KEYWORD
Line: 1
Col: 9
------------------------


Content: v1
Type: IDENTIFIER
Line: 1
Col: 15
------------------------


Content: :
Type: DELIMITER
Line: 1
Col: 17
------------------------


Content: f32
Type: KEYWORD
Line: 1
Col: 19
------------------------


Content: ,
Type: DELIMITER
Line: 1
Col: 22
------------------------


Content: const
Type: KEYWORD
Line: 1
Col: 24
------------------------


Content: v2
Type: IDENTIFIER
Line: 1
Col: 30
------------------------


Content: :
Type: DELIMITER
Line: 1
Col: 32
------------------------


Content: f32
Type: KEYWORD
Line: 1
Col: 34
------------------------


Content: )
Type: DELIMITER
Line: 1
Col: 37
------------------------


Content: ->
Type: DELIMITER
Line: 1
Col: 38
------------------------


Content: f32
Type: KEYWORD
Line: 1
Col: 41
------------------------


Content: :
Type: DELIMITER
Line: 1
Col: 44
------------------------


Content: return
Type: KEYWORD
Line: 2
Col: 5
------------------------


Content: v1
Type: IDENTIFIER
Line: 2
Col: 12
------------------------


Content: +
Type: OP_ARITHMETIC
Line: 2
Col: 14
------------------------


Content: v2
Type: IDENTIFIER
Line: 2
Col: 17
------------------------


Content: ;
Type: DELIMITER
Line: 2
Col: 19
------------------------


Content: end
Type: KEYWORD
Line: 3
Col: 1
------------------------


Content: fun
Type: KEYWORD
Line: 5
Col: 1
------------------------


Content: Div
Type: IDENTIFIER
Line: 5
Col: 5
------------------------


Content: (
Type: DELIMITER
Line: 5
Col: 8
------------------------


Content: const
Type: KEYWORD
Line: 5
Col: 9
------------------------


Content: v1
Type: IDENTIFIER
Line: 5
Col: 15
------------------------


Content: :
Type: DELIMITER
Line: 5
Col: 17
------------------------


Content: f32
Type: KEYWORD
Line: 5
Col: 19
------------------------


Content: ,
Type: DELIMITER
Line: 5
Col: 22
------------------------


Content: const
Type: KEYWORD
Line: 5
Col: 24
------------------------


Content: v2
Type: IDENTIFIER
Line: 5
Col: 30
------------------------


Content: :
Type: DELIMITER
Line: 5
Col: 32
------------------------


Content: f32
Type: KEYWORD
Line: 5
Col: 34
------------------------


Content: )
Type: DELIMITER
Line: 5
Col: 37
------------------------


Content: ->
Type: DELIMITER
Line: 5
Col: 38
------------------------


Content: f32
Type: KEYWORD
Line: 5
Col: 41
------------------------


Content: :
Type: DELIMITER
Line: 5
Col: 44
------------------------


Content: if
Type: KEYWORD
Line: 6
Col: 5
------------------------


Content: (
Type: DELIMITER
Line: 6
Col: 7
------------------------


Content: v2
Type: IDENTIFIER
Line: 6
Col: 8
------------------------


Content: ==
Type: OP_COMPARISON
Line: 6
Col: 10
------------------------


Content: 0
Type: LITERAL_INT
Line: 6
Col: 13
------------------------


Content: )
Type: DELIMITER
Line: 6
Col: 14
------------------------


Content: :
Type: DELIMITER
Line: 6
Col: 15
------------------------


Content: Panic
Type: IDENTIFIER
Line: 7
Col: 9
------------------------


Content: (
Type: DELIMITER
Line: 7
Col: 14
------------------------


Content: Division by zero
Type: LITERAL_STRING
Line: 7
Col: 16
------------------------


Content: )
Type: DELIMITER
Line: 7
Col: 33
------------------------


Content: ;
Type: DELIMITER
Line: 7
Col: 34
------------------------


Content: end
Type: KEYWORD
Line: 8
Col: 5
------------------------


Content: return
Type: KEYWORD
Line: 10
Col: 5
------------------------


Content: v1
Type: IDENTIFIER
Line: 10
Col: 12
------------------------


Content: /
Type: OP_ARITHMETIC
Line: 10
Col: 14
------------------------


Content: v2
Type: IDENTIFIER
Line: 10
Col: 17
------------------------


Content: ;
Type: DELIMITER
Line: 10
Col: 19
------------------------


Content: end
Type: KEYWORD
Line: 11
Col: 1
------------------------


Content: fun
Type: KEYWORD
Line: 13
Col: 1
------------------------


Content: Mul
Type: IDENTIFIER
Line: 13
Col: 5
------------------------


Content: (
Type: DELIMITER
Line: 13
Col: 8
------------------------


Content: const
Type: KEYWORD
Line: 13
Col: 9
------------------------


Content: v1
Type: IDENTIFIER
Line: 13
Col: 15
------------------------


Content: :
Type: DELIMITER
Line: 13
Col: 17
------------------------


Content: f32
Type: KEYWORD
Line: 13
Col: 19
------------------------


Content: ,
Type: DELIMITER
Line: 13
Col: 22
------------------------


Content: const
Type: KEYWORD
Line: 13
Col: 24
------------------------


Content: v2
Type: IDENTIFIER
Line: 13
Col: 30
------------------------


Content: :
Type: DELIMITER
Line: 13
Col: 32
------------------------


Content: f32
Type: KEYWORD
Line: 13
Col: 34
------------------------


Content: )
Type: DELIMITER
Line: 13
Col: 37
------------------------


Content: ->
Type: DELIMITER
Line: 13
Col: 38
------------------------


Content: f32
Type: KEYWORD
Line: 13
Col: 41
------------------------


Content: :
Type: DELIMITER
Line: 13
Col: 44
------------------------


Content: return
Type: KEYWORD
Line: 14
Col: 5
------------------------


Content: v1
Type: IDENTIFIER
Line: 14
Col: 12
------------------------


Content: *
Type: OP_ARITHMETIC
Line: 14
Col: 14
------------------------


Content: v2
Type: IDENTIFIER
Line: 14
Col: 17
------------------------


Content: ;
Type: DELIMITER
Line: 14
Col: 19
------------------------


Content: end
Type: KEYWORD
Line: 15
Col: 1
------------------------


Content: fun
Type: KEYWORD
Line: 17
Col: 1
------------------------


Content: Sub
Type: IDENTIFIER
Line: 17
Col: 5
------------------------


Content: (
Type: DELIMITER
Line: 17
Col: 8
------------------------


Content: const
Type: KEYWORD
Line: 17
Col: 9
------------------------


Content: v1
Type: IDENTIFIER
Line: 17
Col: 15
------------------------


Content: :
Type: DELIMITER
Line: 17
Col: 17
------------------------


Content: f32
Type: KEYWORD
Line: 17
Col: 19
------------------------


Content: ,
Type: DELIMITER
Line: 17
Col: 22
------------------------


Content: const
Type: KEYWORD
Line: 17
Col: 24
------------------------


Content: v2
Type: IDENTIFIER
Line: 17
Col: 30
------------------------


Content: :
Type: DELIMITER
Line: 17
Col: 32
------------------------


Content: f32
Type: KEYWORD
Line: 17
Col: 34
------------------------


Content: )
Type: DELIMITER
Line: 17
Col: 37
------------------------


Content: ->
Type: DELIMITER
Line: 17
Col: 38
------------------------


Content: f32
Type: KEYWORD
Line: 17
Col: 41
------------------------


Content: :
Type: DELIMITER
Line: 17
Col: 44
------------------------


Content: return
Type: KEYWORD
Line: 18
Col: 5
------------------------


Content: v1
Type: IDENTIFIER
Line: 18
Col: 12
------------------------


Content: -
Type: OP_ARITHMETIC
Line: 18
Col: 14
------------------------


Content: v2
Type: IDENTIFIER
Line: 18
Col: 17
------------------------


Content: ;
Type: DELIMITER
Line: 18
Col: 19
------------------------


Content: end
Type: KEYWORD
Line: 19
Col: 1
------------------------


Content: Add
Type: IDENTIFIER
Line: 21
Col: 1
------------------------


Content: (
Type: DELIMITER
Line: 21
Col: 4
------------------------


Content: 10
Type: LITERAL_INT
Line: 21
Col: 5
------------------------


Content: ,
Type: DELIMITER
Line: 21
Col: 7
------------------------


Content: 20
Type: LITERAL_INT
Line: 21
Col: 9
------------------------


Content: )
Type: DELIMITER
Line: 21
Col: 11
------------------------


Content: ;
Type: DELIMITER
Line: 21
Col: 12
------------------------


Content: Div
Type: IDENTIFIER
Line: 22
Col: 1
------------------------


Content: (
Type: DELIMITER
Line: 22
Col: 4
------------------------


Content: 10
Type: LITERAL_INT
Line: 22
Col: 5
------------------------


Content: ,
Type: DELIMITER
Line: 22
Col: 7
------------------------


Content: 20
Type: LITERAL_INT
Line: 22
Col: 9
------------------------


Content: )
Type: DELIMITER
Line: 22
Col: 11
------------------------


Content: ;
Type: DELIMITER
Line: 22
Col: 12
------------------------


Content: Mul
Type: IDENTIFIER
Line: 23
Col: 1
------------------------


Content: (
Type: DELIMITER
Line: 23
Col: 4
------------------------


Content: 10
Type: LITERAL_INT
Line: 23
Col: 5
------------------------


Content: ,
Type: DELIMITER
Line: 23
Col: 7
------------------------


Content: 20
Type: LITERAL_INT
Line: 23
Col: 9
------------------------


Content: )
Type: DELIMITER
Line: 23
Col: 11
------------------------


Content: ;
Type: DELIMITER
Line: 23
Col: 12
------------------------


Content: Sub
Type: IDENTIFIER
Line: 24
Col: 1
------------------------


Content: (
Type: DELIMITER
Line: 24
Col: 4
------------------------


Content: 10
Type: LITERAL_INT
Line: 24
Col: 5
------------------------


Content: ,
Type: DELIMITER
Line: 24
Col: 7
------------------------


Content: 20
Type: LITERAL_INT
Line: 24
Col: 9
------------------------


Content: )
Type: DELIMITER
Line: 24
Col: 11
------------------------


Content: ;
Type: DELIMITER
Line: 24
Col: 12
------------------------


Content: 
Type: END_OF_FILE
Line: 25
Col: 0
------------------------

