
Content: [0mvar[0m
Type: [0mKEYWORD[0m
Line: [0m1[0m
Col: [0m1[0m
------------------------

[0m
Content: [0minteger_8bits[0m
Type: [0mIDENTIFIER[0m
Line: [0m1[0m
Col: [0m5[0m
------------------------

[0m
Content: [0m:[0m
Type: [0mDELIMITER[0m
Line: [0m1[0m
Col: [0m18[0m
------------------------

[0m
Content: [0mi8[0m
Type: [0mKEYWORD[0m
Line: [0m1[0m
Col: [0m20[0m
------------------------

[0m
Content: [0m=[0m
Type: [0mOP_ASSIGNMENT[0m
Line: [0m1[0m
Col: [0m24[0m
------------------------

[0m
Content: [0m10[0m
Type: [0mLITERAL_INT[0m
Line: [0m1[0m
Col: [0m26[0m
------------------------

[0m
Content: [0m;[0m
Type: [0mDELIMITER[0m
Line: [0m1[0m
Col: [0m28[0m
------------------------

[0m
Compilation completed in: 1ms
[0m
