<literal-int>    = [0-9]+
<literal-float>  = [0-9]+ "." [0-9]+
<literal-bool>   = "true" | "false"
<literal-char>   = "'" . "'" 
<literal-string> = '"' .* '"'

<literal-value> = <literal-int>
    | <literal-float>
    | <literal-bool>
    | <literal-char>
    | <literal-string>
    | <struct-instance>

<type-native> = "i8" | "i16" | "i32" | "i64" | "f32" | "f64" | "bool" | "string" | "void"

<identifier>  = [a-zA-Z_][a-zA-Z0-9_]*

<type-list>   = <type-identifier> ( "," <type-identifier> )*

<call-function> = <identifier> "(" [ <argument-list> ] ")"

<op-arithmetic> = "+" | "-" | "*" | "/" | "^"
<op-logical>    = "||" | "&&" | "!"
<op-comparison> = "==" | "!=" | ">" | "<" | ">=" | "<="
<op-bitwise>    = "|" | "&"

<argument-list> = <expression> ("," <expression>)*

<condition-stmt> = 'if' '(' <expression> ')' <block> 
                    ( 'elif' '(' <expression> ')' <block> )* [ 'else' <block> ] 
                    'end'

<interator> = 'in' | 'of'

<for-stmt> = 'for' '(' <constant-declaration> <interator> <type-identifier>* ')' <block-scope> 

<while-stmt> = 'while' '(' <expression> ')' <block-scope>

<loop-declaration> = <for-stmt> | <while-stmt>

<return-stmt> = 'return' ( <expression> ) ';'

<statement> = <data-declaration> | <call-function> ";" | <condition-stmt> | <loop-declaration> | <return-stmt>

<block-scope> = ':' <statement>* 'end'

<expression> = <literal-value> | <call-function> | <identifier> | <anonimous-function> | '(' <expression> ')'

<variable-declaration> = 'var' <identifier> ':' <type-identifier>
<constant-declaration> = 'const' <identifier> ':' <type-identifier>

<data-declaration> = (<variable-declaration> | <constant-declaration>) [ '=' <expression> ] ';'

<struct-value-assignment> = <identifier> ':' <literal-value>

<struct-value-assign-list> = <struct-value-assignment> [',' <struct-value-assignment>]*

<struct-instance> = <identifier> '{' <struct-value-assign-list> '}'

<struct-block-scope> = ':' <data-declaration> 'end'

<struct-inherit> = ['!'] <identifier>

<struct-declaration> = 'struct' <identifier> [ 'extends' <struct-inherit> (',' <struct-inherit>)* ] <struct-block-scope>

<parameter>      = (<constant-declaration> | <variable-declaration>) [ "=" <literal-value> ]
<parameter-list> = <parameter> ( "," <parameter> )*

<type-identifier> = <type-native> | <identifier> | <type-function>

<type-function> = 'fun' '(' [ <type-list> ] ')' '->' <type-identifier>

<function-declaration> = 'fun' [ <identifier> '::' ] <identifier> '(' <parameter-list> ')' '->' <type-identifier> <block-scope>

<anonimous-function> = '(' <parameter-list> ')' '->' <type-identifier> <block-scope>

<extern-declaration> = 'extern' 'fun' <identifier> '(' [ <type-list> ] ')' '->' <type-identifier> ';'

<module-declaration> = 'module' <identifier> ( '::' <identifier> )* ';'

<import-declaration> = 'import' <identifier> ( '::' <identifier> )* ';'


